name: Release and Build Docker Image

on:
  push:
    branches: ['*']
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write  
  id-token: write


jobs:
  build-every-commit:
    name: Build on every commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

  release:
    name: Run Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v3
        with:
          release-type: node
          bump-minor-pre-major: true
          package-name: "fleetsim-ui"
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

  build-and-push-docker:
    name: Build and Push Docker image
    needs: release
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'chore(main): release')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/fleetsim-ui
          VERSION=$(node -p "require('./package.json').version")
          echo "Docker version: $VERSION"
          docker build -t $IMAGE_NAME:$VERSION .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/fleetsim-ui
          VERSION=$(node -p "require('./package.json').version")
          docker push $IMAGE_NAME:$VERSION